### ISSUE TITLE
<tab>-ing away while select dialog is open

### ISSUE THREAD

**Issue by shanewholloway** [siit-dev/better-select#1]
I noticed that `<tab>`-ing away from an open select dialog does not close the dialog like the built-in system widget.

Thanks for making this! I love the advancement with `better-select` webcomponent, as I'm a fan of both webcomponents and various `select` widget projects.

**Comment by bogdanbeniaminb** [comment]
@shanewholloway Thank you! Yes, you're right. Fixed.

**Comment by bogdanbeniaminb** [comment]
@shanewholloway Also, thank you very much for your interest and your kind words! I'm a fan of web components too!
